import { AI_TOOLS, PURPOSES } from "../constants.js";

// ── Validation ────────────────────────────────
export function validateForm(form) {
  

  if (!form.name.trim())              return "Please enter your full name.";
  if (!isValidEmail(form.email))      return "Please enter a valid email address.";
  if (!form.tool)                      return "Please select or specify an AI tool.";
  if (!isValidAmount(form.monthlySpend)) return "Please enter a valid monthly spend (0 or more).";
  if (!form.primaryUseCase)                   return "Please select or specify the purpose of use.";

  return null; // null = no error
}

function isValidEmail(email) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function isValidAmount(val) {
  return val !== "" && !isNaN(Number(val)) && Number(val) >= 0;
}

// ── API call to fetch audit report ────────────────────────────────
export async function
fetchAuditReport(form) {

  console.log(
    "Submitting form data:",
    form
  );



  const payload = {

    tools: [

      {
        tool:
          form.tool,

        plan:
          form.plan,

        monthlySpend:
          Number(form.monthlySpend),

        seats:
          Number(form.seats)
      }

    ],

    teamSize:
      Number(form.teamSize),

    useCase:
      form.primaryUseCase
  };



  console.log(
    "Final payload:",
    payload
  );



  const response =
    await fetch(

      "http://localhost:5000/api/audit",

      {
        method: "POST",

        headers: {
          "Content-Type":
            "application/json"
        },

        body:
          JSON.stringify(payload)
      }
    );



  if (!response.ok) {

    throw new Error(
      "Failed to generate audit"
    );
  }
   
  return await response.json();
}

// ── Download report as .txt ───────────────────
export function downloadReportAsTxt(report) {
  const { meta, executiveSummary, timeSaved, costSavings, roi,
          efficiencyScore, riskLevel, recommendations, complianceNote } = report;

  const lines = [
    "╔══════════════════════════════════════════════════════════╗",
    "║              AI USAGE AUDIT REPORT                      ║",
    "╚══════════════════════════════════════════════════════════╝",
    "",
    `Generated:   ${meta.generatedAt}`,
    `Report ID:   AUD-${Date.now()}`,
    "",
    "── AUDITED SUBJECT ───────────────────────────────────────",
    `Name:        ${meta.name}`,
    `Email:       ${meta.email}`,
    `AI Tool:     ${meta.tool}`,
    `Spend:       $${meta.spent}/month`,
    `Purpose:     ${meta.purpose}`,
    "",
    "── EXECUTIVE SUMMARY ─────────────────────────────────────",
    executiveSummary,
    "",
    "── KEY METRICS ───────────────────────────────────────────",
    `Time Saved:         ${timeSaved} hours/month`,
    `Cost Savings:       $${costSavings}/month`,
    `ROI:                ${roi}%`,
    `Net Gain:           $${costSavings - meta.spent}/month`,
    `Efficiency Score:   ${efficiencyScore}/10`,
    `Risk Level:         ${riskLevel}`,
    "",
    "── RECOMMENDATIONS ───────────────────────────────────────",
    ...recommendations.map((r, i) => `${i + 1}. ${r}`),
    "",
    "── COMPLIANCE NOTE ───────────────────────────────────────",
    complianceNote,
    "",
    "─────────────────────────────────────────────────────────",
    "Generated by AI Audit System · Powered by Claude AI",
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `ai-audit-${meta.name.replace(/\s+/g, "-").toLowerCase()}-${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}